### ISSUE TITLE
How to connect my handlers to be used in Formik

### ISSUE THREAD

**Issue by LDRMuse** [Claim-Academy-JS/capstone-starter-LDRMuse#1]
I want to be able to use my handle functions but not quite sure how to incorporate these into Formik. Do I call the functions inside Formik or do I create the functions in onSubmit?

https://github.com/Claim-Academy-JS/capstone-starter-LDRMuse/blob/ead6e4f650f22c0ca30e1f21388f06e9d84a214f/client/src/components/views/GetStarted.js#L12-L52

**Comment by manavm1990** [comment]
You'll use the ['Formik submitter,'](https://github.com/Claim-Academy-JS/capstone-starter-LDRMuse/blob/ead6e4f650f22c0ca30e1f21388f06e9d84a214f/client/src/components/views/GetStarted.js#L49) which collects all of your values for you.
You can move the code you show ☝️ into here...or just start by `log` to get the idea 💡 .

**Comment by manavm1990** [comment]
[This commit](https://github.com/Claim-Academy-JS/capstone-starter-LDRMuse/commit/f778dd4dab52f73cbf91533a43a9839978fffaf1) includes a `TODO{melissa.heying}` showing where this is.
